#!/bin/sh
PID_FILE=/usr/src/app/tmp/unicorn.pid
[ -f "$PID_FILE" ] && rm "$PID_FILE"

bundle exec rake db:create db:migrate db:seed
if [ $? -eq 0 ]
then
   echo "DB migration: successful"
else
   echo "Error on DB migration"
   exit 1
fi

bundle exec unicorn -c config/unicorn/docker.rb -E docker
