default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: thorn_development

test:
  <<: *default
  database: thorn_test

production:
  <<: *default
  database: thorn_production
  username: thorn
  password: thorn
