default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: thorn_development

test:
  <<: *default
  database: thorn_test

production:
  <<: *default
  database: thorn
  username: thorn
  password: thornsecret
  host: citron.ctweb.inweb.org.br

docker:
  <<: *default
  database: thorn
  host: mysql
