default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: torn_development

test:
  <<: *default
  database: torn_test

production:
  <<: *default
  database: torn_production
  username: torn
  password: torn
