# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1e8b6fafd60e15c7d58942fa9592f39c312bc9caa5cbe2185f0d4ac7e0fd6d1196ca16c12a3a689d7a74e4c93c059b04c8e6f8e51bedae2ae8e57e92b512453
  email_provider_username: lemonade.demo.lsl
  email_provider_password: lsl12345

test:
  secret_key_base: f598f0eba4a9a2c16c4af8b92c1f04d7270213e060b6c6ecb73a7b8e612ab255a51d4b945375c26d0c7e4698d76458e2b02aa72ed4cbb58d8c32fef0dd352771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
